// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbUoxa3XFRMpLHj9wNc4awuo61xl9678U',
    appId: '1:1097214336094:web:af37d7f62b99ed3bd5a8cf',
    messagingSenderId: '1097214336094',
    projectId: 'meeraprabhu-4159a',
    authDomain: 'meeraprabhu-4159a.firebaseapp.com',
    storageBucket: 'meeraprabhu-4159a.firebasestorage.app',
    measurementId: 'G-7ZQH6R0PG6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsUhDyM09d0uiPXTNN_4KUIUl7jIrFoAA',
    appId: '1:1097214336094:android:cf55f97f21f2f196d5a8cf',
    messagingSenderId: '1097214336094',
    projectId: 'meeraprabhu-4159a',
    storageBucket: 'meeraprabhu-4159a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSI3Mmr3HDjfJZQ1F9BMkup1RxhPi6R9g',
    appId: '1:1097214336094:ios:7da4d84f41531bc2d5a8cf',
    messagingSenderId: '1097214336094',
    projectId: 'meeraprabhu-4159a',
    storageBucket: 'meeraprabhu-4159a.firebasestorage.app',
    iosBundleId: 'com.yencode.fintrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSI3Mmr3HDjfJZQ1F9BMkup1RxhPi6R9g',
    appId: '1:1097214336094:ios:7da4d84f41531bc2d5a8cf',
    messagingSenderId: '1097214336094',
    projectId: 'meeraprabhu-4159a',
    storageBucket: 'meeraprabhu-4159a.firebasestorage.app',
    iosBundleId: 'com.yencode.fintrack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBbUoxa3XFRMpLHj9wNc4awuo61xl9678U',
    appId: '1:1097214336094:web:34c5c2571208a6f3d5a8cf',
    messagingSenderId: '1097214336094',
    projectId: 'meeraprabhu-4159a',
    authDomain: 'meeraprabhu-4159a.firebaseapp.com',
    storageBucket: 'meeraprabhu-4159a.firebasestorage.app',
    measurementId: 'G-LJMDG5Z5WH',
  );

}