// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXByWwhIAaT20GvrW5_Lo_c_ReFeEzkSE',
    appId: '1:749541207800:web:e03eccbe94a2952b1d150d',
    messagingSenderId: '749541207800',
    projectId: 'cardreminder-ade76',
    authDomain: 'cardreminder-ade76.firebaseapp.com',
    storageBucket: 'cardreminder-ade76.firebasestorage.app',
    measurementId: 'G-D94KL87LPM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqrSB7TjdN0BjSl5ZeTIlIveCMieFAnQ8',
    appId: '1:749541207800:android:1901a36ef36aa3e41d150d',
    messagingSenderId: '749541207800',
    projectId: 'cardreminder-ade76',
    storageBucket: 'cardreminder-ade76.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiwId2dg0oFQo35coIfPR3wBuxVwfrrxg',
    appId: '1:749541207800:ios:234b3a5bf4550f561d150d',
    messagingSenderId: '749541207800',
    projectId: 'cardreminder-ade76',
    storageBucket: 'cardreminder-ade76.firebasestorage.app',
    iosBundleId: 'com.yencode.fintrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDiwId2dg0oFQo35coIfPR3wBuxVwfrrxg',
    appId: '1:749541207800:ios:234b3a5bf4550f561d150d',
    messagingSenderId: '749541207800',
    projectId: 'cardreminder-ade76',
    storageBucket: 'cardreminder-ade76.firebasestorage.app',
    iosBundleId: 'com.yencode.fintrack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXByWwhIAaT20GvrW5_Lo_c_ReFeEzkSE',
    appId: '1:749541207800:web:b8923056264c44ea1d150d',
    messagingSenderId: '749541207800',
    projectId: 'cardreminder-ade76',
    authDomain: 'cardreminder-ade76.firebaseapp.com',
    storageBucket: 'cardreminder-ade76.firebasestorage.app',
    measurementId: 'G-YCS6S8XWXF',
  );
}
